# Generated by Django 3.2.3 on 2021-06-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
