# Generated by Django 3.2.3 on 2021-06-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
